package model;
// Generated 09-abr-2019 16:59:43 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CollaboratesId generated by hbm2java
 */
public class CollaboratesId  implements java.io.Serializable {


     private String codexpert;
     private String codcaso;
     private Date datec;

    public CollaboratesId() {
    }

    public CollaboratesId(String codexpert, String codcaso, Date datec) {
       this.codexpert = codexpert;
       this.codcaso = codcaso;
       this.datec = datec;
    }
   
    public String getCodexpert() {
        return this.codexpert;
    }
    
    public void setCodexpert(String codexpert) {
        this.codexpert = codexpert;
    }
    public String getCodcaso() {
        return this.codcaso;
    }
    
    public void setCodcaso(String codcaso) {
        this.codcaso = codcaso;
    }
    public Date getDatec() {
        return this.datec;
    }
    
    public void setDatec(Date datec) {
        this.datec = datec;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CollaboratesId) ) return false;
		 CollaboratesId castOther = ( CollaboratesId ) other; 
         
		 return ( (this.getCodexpert()==castOther.getCodexpert()) || ( this.getCodexpert()!=null && castOther.getCodexpert()!=null && this.getCodexpert().equals(castOther.getCodexpert()) ) )
 && ( (this.getCodcaso()==castOther.getCodcaso()) || ( this.getCodcaso()!=null && castOther.getCodcaso()!=null && this.getCodcaso().equals(castOther.getCodcaso()) ) )
 && ( (this.getDatec()==castOther.getDatec()) || ( this.getDatec()!=null && castOther.getDatec()!=null && this.getDatec().equals(castOther.getDatec()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodexpert() == null ? 0 : this.getCodexpert().hashCode() );
         result = 37 * result + ( getCodcaso() == null ? 0 : this.getCodcaso().hashCode() );
         result = 37 * result + ( getDatec() == null ? 0 : this.getDatec().hashCode() );
         return result;
   }   


}


