package model;
// Generated 09-abr-2019 16:59:43 by Hibernate Tools 4.3.1



/**
 * Collaborates generated by hbm2java
 */
public class Collaborates  implements java.io.Serializable {


     private CollaboratesId id;
     private Expert expert;
     private Policialcase policialcase;
     private String descripcion;

    public Collaborates() {
    }

	
    public Collaborates(CollaboratesId id, Expert expert, Policialcase policialcase) {
        this.id = id;
        this.expert = expert;
        this.policialcase = policialcase;
    }
    public Collaborates(CollaboratesId id, Expert expert, Policialcase policialcase, String descripcion) {
       this.id = id;
       this.expert = expert;
       this.policialcase = policialcase;
       this.descripcion = descripcion;
    }
   
    public CollaboratesId getId() {
        return this.id;
    }
    
    public void setId(CollaboratesId id) {
        this.id = id;
    }
    public Expert getExpert() {
        return this.expert;
    }
    
    public void setExpert(Expert expert) {
        this.expert = expert;
    }
    public Policialcase getPolicialcase() {
        return this.policialcase;
    }
    
    public void setPolicialcase(Policialcase policialcase) {
        this.policialcase = policialcase;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


