package model;
// Generated 09-abr-2019 16:59:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Expert generated by hbm2java
 */
public class Expert  implements java.io.Serializable {


     private String codexpert;
     private String name;
     private String country;
     private Character sex;
     private String specialism;
     private Set collaborateses = new HashSet(0);

    public Expert() {
    }

	
    public Expert(String codexpert, String name, String country, String specialism) {
        this.codexpert = codexpert;
        this.name = name;
        this.country = country;
        this.specialism = specialism;
    }
    public Expert(String codexpert, String name, String country, Character sex, String specialism, Set collaborateses) {
       this.codexpert = codexpert;
       this.name = name;
       this.country = country;
       this.sex = sex;
       this.specialism = specialism;
       this.collaborateses = collaborateses;
    }
   
    public String getCodexpert() {
        return this.codexpert;
    }
    
    public void setCodexpert(String codexpert) {
        this.codexpert = codexpert;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public Character getSex() {
        return this.sex;
    }
    
    public void setSex(Character sex) {
        this.sex = sex;
    }
    public String getSpecialism() {
        return this.specialism;
    }
    
    public void setSpecialism(String specialism) {
        this.specialism = specialism;
    }
    public Set getCollaborateses() {
        return this.collaborateses;
    }
    
    public void setCollaborateses(Set collaborateses) {
        this.collaborateses = collaborateses;
    }




}


